language: node_js
os:
  - linux
  - macos
  - windows
node_js:
  - '0.8'
  - '0.10'
  - '0.12'
  - '4'
  - '6'
  - '8'
  - '10'
  - '12'
  - 'stable'
matrix:
  exclude:
    - node_js: 'stable'
      os: 'windows'
  include:
    - node_js: 'latest'
      os: 'windows'
before_install:
  - 'if [[ $TRAVIS_OS_NAME != windows ]]; then nvm install-latest-npm; fi'
