language: node_js
os:
  - linux
  - macos
  - windows
node_js:
  - '0.8'
  - '0.10'
  - '0.12'
  - '4'
  - '6'
  - '8'
  - '10'
  - '12'
  - 'stable'
matrix:
  exclude:
    - node_js: 'stable'
      os: 'windows'
  include:
    - node_js: 'latest'
      os: 'windows'
before_install:
  - 'if [[ $TRAVIS_OS_NAME != windows ]]; then nvm install-latest-npm; fi'
  - 'if [[ $TRAVIS_OS_NAME == windows ]] && [[ $TRAVIS_NODE_VERSION == 0.8 ]]; then npm install -g npm@1.4.28 && npm install -g npm@4.5.x; fi'
